### ISSUE TITLE
Support UltraScale devices

### ISSUE THREAD

**Issue by wirthlin** [byuccl/bfat#51] opened 2023-06-02 17:24 UTC
BFAT currently only supports 7 series device based o the [Project Xray](https://github.com/f4pga/prjxray). It would be nice to support UltraScale device based on [Project uray](https://github.com/f4pga/prjuray).

**Comment by ethanrcampbell02** [comment] 2023-06-02 19:05
Closing because this is a duplicate of issue #47.

**Closed as completed by ethanrcampbell02** 2023-06-02 19:05 UTC
